### ISSUE TITLE
docker image is dead after starting

### ISSUE THREAD

**Issue by sirdir** [seedpockets/ukrainian-warship#1]
when running `docker run -ti --rm sunflowerpockets/ukrainian-warship:latest`
```
Acquiring targets...
⣽panic: Could not get targets...

goroutine 1 [running]:
github.com/seedpockets/ukrainian-warship/cmd.Kill(0x200)
        /app/cmd/kill.go:105 +0x309
github.com/seedpockets/ukrainian-warship/cmd.AutoKill(0xc0001bdd88)
        /app/cmd/kill.go:73 +0x8f
github.com/seedpockets/ukrainian-warship/cmd.glob..func1(0xc26460, {0x8733fa, 0x0, 0x0})
        /app/cmd/kill.go:43 +0x2f
github.com/spf13/cobra.(*Command).execute(0xc26460, {0xc5fdc8, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc266e0)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/seedpockets/ukrainian-warship/cmd.Execute()
        /app/cmd/root.go:46 +0x25
main.main()
        /app/main.go:21 +0x17
```

**Comment by seedpockets** [comment]
I'm currently working on a fix for this.

**Comment by seedpockets** [comment]
I rewrote the kill command, this should solve your issue.
